export const FindingTypes = {
  PORT_EXPOSED:           'PORT_EXPOSED',
  PORT_CHANGE:            'PORT_CHANGE',
  TLS_CHECK:              'TLS_CHECK',
  TLS_EXPIRING:           'TLS_EXPIRING',
  TLS_CHANGE:             'TLS_CHANGE',
  HTTP_HEALTH:            'HTTP_HEALTH',
  HTTP_CHANGE:            'HTTP_CHANGE',
  SECURITY_HEADER_MISSING:'SECURITY_HEADER_MISSING',
  DNS_RECORD_CHANGE:      'DNS_RECORD_CHANGE',
  DNS_NS_CHANGE:          'DNS_NS_CHANGE',
  DNS_MX_CHANGE:          'DNS_MX_CHANGE',
  DNS_TXT_CHANGE:         'DNS_TXT_CHANGE',
  DNS_SPF_MISSING:        'DNS_SPF_MISSING',
  DNS_DMARC_MISSING:      'DNS_DMARC_MISSING',
  DNS_DMARC_WEAK_POLICY:  'DNS_DMARC_WEAK_POLICY',
  DNS_CAA_MISSING:        'DNS_CAA_MISSING',
  WHOIS_EXPIRING:         'WHOIS_EXPIRING',
  WHOIS_CHANGE:           'WHOIS_CHANGE',
  GEOIP_CHANGE:                 'GEOIP_CHANGE',
  ASN_CHANGE:                   'ASN_CHANGE',
  ROBOTS_SENSITIVE_PATH_EXPOSED:'ROBOTS_SENSITIVE_PATH_EXPOSED',
  ROBOTS_CHANGE:                'ROBOTS_CHANGE',
  PHISHING_DETECTED:                'PHISHING_DETECTED',
  MALICIOUS_REPUTATION_DETECTED:    'MALICIOUS_REPUTATION_DETECTED',
  BREACH_EXPOSURE_DETECTED:         'BREACH_EXPOSURE_DETECTED',
  OTX_PULSE_DETECTED:               'OTX_PULSE_DETECTED',
  OTX_MALWARE_ACTIVITY_DETECTED:    'OTX_MALWARE_ACTIVITY_DETECTED',
  SQL_INJECTION_SUSPECTED:          'SQL_INJECTION_SUSPECTED',
} as const;

export type FindingType = typeof FindingTypes[keyof typeof FindingTypes];

export const FINDING_TYPES: FindingType[] = Object.values(FindingTypes);
